### ISSUE TITLE
Parameters start and end

### ISSUE THREAD

**Issue by b2m** [BioroboticsLab/bb_binary#2]
When using parameters like *start* and *end* it should be documented and tested whether they are inclusive or exclusive.

Problem found in [iter_fnames](https://github.com/BioroboticsLab/bb_binary/blob/master/python/bb_binary/__init__.py#L449)

**Comment by berleon** [comment]
The bug was fixed in commit https://github.com/BioroboticsLab/bb_binary/commit/d86e9194ac02bc7b17573fe11cd8199239bf5a66

Is the documentation good enough?

**Comment by b2m** [comment]
As expected great work =)
