### ISSUE TITLE
New requirement: iter_frames

### ISSUE THREAD

**Issue by b2m** [BioroboticsLab/bb_binary#3]
It would be helpful if there would be a function `iter_frames(start=None, end=None, cam=None)` analogous to [iter_fnames](https://github.com/BioroboticsLab/bb_binary/blob/master/python/bb_binary/__init__.py#L449).

This function would iterate through frames in a given time range.

Start is **in**clusive, end is **ex**clusive.

No start or end given: behavior `like iter_fnames`.

**Comment by berleon** [comment]
Would the function simple yield raw Cap'N Proto frames? Or would they also be converted to
numpy arrays? What if you are interested in the `cam_id` which is stored only in the `FrameContainer` at the top level? Would this use-case be out of scope of the `iter_frames` function?
I personally prefer `start` till `end` like the python `range` function.

**Comment by b2m** [comment]
> I personally prefer start till end like the python range function.

Agreed

Regarding the `cam_id`: I do not like the idea of *dropping* the information for a convenience method like `iter_frames`. So here are three suggestions:

1. Move `cam_id` from `FrameContainer` to `Frame` in the Schema, making it possible to store frames from different cameras in one `FrameContainer`.
2. yield the `FrameContainer` object as dictionary (without frames) as second return value along with the `Frame` object
3. Convert the `Frame` to a python dictionary and add the missing information from the `FrameContainer`.

Otherwise it could be argued, that if you **need** the `cam_id` or other information from `FrameContainer`, use `iter_fnames` or make several passes with the `cam` parameter of `iter_frames`.

I would prefer option 2 with the `FrameContainer` as second return value.
The calling code then would look something like:

```python
from numpy.lib.recfunctions import append_fields
for frame, fc in repo.iter_frames(start, end):
    arr = convert_frame_to_numpy(frame)
    cam_col = np.repeat(fc.camId, arr.shape[0])
    arr_ext = append_fields(arr, 'cam_id', cam_col, usemask=False)
    # ... do something with arr_ext like stacking
```

We also could enhance `convert_frame_to_numpy()` to automatically add and fill columns like:

```python
for frame, fc in repo.iter_frames(start, end):
    arr = convert_frame_to_numpy(frame, add_columns={'cam_id': fc.camId})
```

From my perspective this would be the most practical solution.

**Comment by berleon** [comment]
> I would prefer option 2 with the FrameContainer as second return value.
I would prefer that too. That way the caller can always get the values he is interested in.

I also like you suggested enhancement, but you have to decide how useful it would be for the tracking.

You already had some basic code for `iter_frames`, right? Do you want to implement it?
