### ISSUE TITLE
Interval problem with Repository.iter_fnames()

### ISSUE THREAD

**Issue by b2m** [BioroboticsLab/bb_binary#9]
The method [Repository.iter_fnames()](http://bb-binary.readthedocs.io/en/latest/api/repository.html#bb_binary.repository.Repository.iter_fnames) accepts the keyword arguments `begin` and `end`. When `begin` and `end` are in the **same** interval, the method will yield nothing. Or to use the illustration from the docstring:

    Files:            A                 B 
    Frames:    |---------------|---------------|
                   ⬆      ⬆
                 begin   end

Instead of `A` no filename is yielded.

**Comment by nebw** [comment]
fixed in de5c84f
